services:
  server:
    image: bingo-back-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3001:3001
    container_name: bingo-back-dev
  app:
    image: bingo-front-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    container_name: bingo-front-dev
    depends_on:
      - server